### ISSUE TITLE
Crash on World start?

### ISSUE THREAD

**Issue by HyperMan19680** [Wehavecookies56/Kingdom-Keys#1]
Yeah, when I try to load a world, I get this crash.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 12/31/20 6:40 PM
Description: Exception in server tick loop

com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.2.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler$$Lambda$8122/1417738042.apply(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$8121/1685836689.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:87) ~[?:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:95) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5872639536 bytes (5600 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3%20(1).jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3%20(1).jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3%20(1).jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.41
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		CyclopsCore-1.15.2-1.8.4.jar Cyclops Core {cyclopscore@1.8.4 DONE}
		TreeChop-1.15.2-0.10.jar treechop {treechop@0.10 DONE}
		smartphone-1.15.2-1.1.0.jar Smartphone {smartphone@1.15.2-1.1.0 DONE}
		fullbrightnesstoggle_1.15.2-1.1.jar Full Brightness Toggle {fullbrightnesstoggle@1.1 DONE}
		SimplyJetpacks2-1.15.2-2.5.3.4.jar Simply Jetpacks 2 {simplyjetpacks@1.15.2-2.5.3.4 DONE}
		Floocraft+1.15.2-1.13.0.jar Floocraft {floocraftft@1.13.0 DONE}
		forge-1.15.2-geckolib-2.0.0.jar Geckolib {geckolib@2.0.0 DONE}
		Redstone_Lantern+1.15.2-1.0.0.jar Redstone Lantern Mod {redstone_lantern@1.15.2-1.0.0 DONE}
		terrible_chest-1.15.2-2.jar Terrible Chest {terrible_chest@1.15.2-2 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		EverlastingAbilities-1.15.2-1.6.3.jar EverlastingAbilities {everlastingabilities@1.6.3 DONE}
		Scannable-MC1.15.2-1.7.1.14.jar Scannable {scannable@1.7.1.14 DONE}
		ProjectE-1.15.2-PE1.0.4.jar ProjectE {projecte@1.0.4 DONE}
		music_player-1.15.2-2.2.1.110.jar Music Player {musicplayer@2.2.1.110 DONE}
		Guide-API-VP-1.15.2-2.2.1.jar Guide-API VP {guideapi-vp@2.2.1 DONE}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d DONE}
		goldenhopper-1.1.1-1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
		ForgeEndertech-1.15.2-6.0.4.0-build.0044.jar Forge Endertech {forgeendertech@6.0.4.0 DONE}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 DONE}
		dankstorage-2.6.jar Dank Storage {dankstorage@2.6 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		TravelersBackpack-1.15.2-4.0.8.jar Traveler's Backpack {travelersbackpack@4.0.8 DONE}
		NoFog-1.15b1.jar NoFog {nofog@1.0.1 DONE}
		AdHooks-1.15.2-5.1.0.0-build.0046.jar Advanced Hook Launchers {adhooks@5.1.0.0 DONE}
		good-nights-sleep-1.15.2-1.1.5.jar Good Night's Sleep {good_nights_sleep@1.1.5 DONE}
		charginggadgets-1.0.0.jar Charging Gadgets {charginggadgets@1.0.0 DONE}
		MutantBeasts-1.15.2-1.0.8.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.8 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.1018 (1).jar Reliquary {xreliquary@1.15.2-1.3.4.1018 DONE}
		pneumaticcraft-repressurized-1.15.2-1.5.2-83.jar PneumaticCraft: Repressurized {pneumaticcraft@1.15.2-1.5.2-83 DONE}
		wizardstaff-1.15.2-1.3.0.jar Wizard Staff {wizard-staff@1.15.2-1.3.0 DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		ForgivingVoid_1.15.1-4.0.0.jar Forgiving Void {forgivingvoid@4.0.0 DONE}
		sworddisplay-1.15.2-1.4.1..jar Sword Displays {sworddisplay@1.15.2-1.4.1. DONE}
		mahoutsukai-1.15.2-v1.24.1.jar Mahou Tsukai {mahoutsukai@1.15.2-v1.24.1 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		iChunUtil-1.15.2-8.0.3.jar iChunUtil {ichunutil@8.0.3 DONE}
		Miraculous-a1.8-1.15.2.jar Miraculous: Tales Of Ladyblock & Craft Noir {miraculous@a1.8 DONE}
		mininggadgets-1.3.5.jar Mining Gadgets {mininggadgets@1.3.5 DONE}
		Fancy+Fluid+Storage-1.15.2-3.0.5.jar Fancy Fluid Storage {ffs@3.0.5 DONE}
		forge-1.15.2-31.2.41-universal.jar Forge {forge@31.2.41 DONE}
		shetiphiancore-1.15-3.7.4.jar ShetiPhian-Core {shetiphiancore@3.7.4 DONE}
		MmmMmmMmmMmm.jar MmmMmmMmmMmm {dummmmmmy@1.0.0 DONE}
		warp-radial-1.15.2-1.0.1.jar Wrap Radial {warpradial@1.0.1 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		PathToDirt-1.0.2-mc1.15.2.jar Path to Dirt {pathtodirt@1.0.2-mc1.15.2 DONE}
		forge-1.15.2-31.2.41-client.jar Minecraft {minecraft@1.15.2 DONE}
		Capsule-1.15.2-4.0.43.jar Capsule {capsule@1.15.2-4.0.43 DONE}
		BeeBarker-1.15.2-8.0.0.jar Bee Barker {beebarker@8.0.0 DONE}
		voice_chat-1.15.2-0.1.0.3.jar Voice Chat {voicechat@0.1.0.3 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		surrounding-indicators-1.15.2-1.1.0.jar Surrounding Indicators {surrounding_indicators@1.1.0 DONE}
		invisiblights-forge-5.0.jar InvisibLights {invisiblights@5.0 DONE}
		nopotionshift_1.15.2-1.4.0.jar No Potion Shift {nopotionshift@1.4.0 DONE}
		CreativeCore_v2.0.5_mc1.15.2.jar CreativeCore {creativecore@2.0.0 DONE}
		movingelevators-1.2.29-mc1.15.jar Moving Elevators {movingelevators@1.2.29 DONE}
		Ding-1.15.2-1.2.0.jar Ding {ding@1.2.0 DONE}
		PlayerEx-1.0.0-1.15.2.jar Player Ex {playerex@1.0.0 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		mermaidtail-1.4.jar Mermaid Tail Mod {mermaidtail@1.15.2-1.4.0 DONE}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 DONE}
		Patchouli-1.15.2-1.2-35 (3).jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		Xaeros_Minimap_20.30.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.30.1 DONE}
		collective-1.15.2-1.51.jar Collective {collective@1.51 DONE}
		explosiont-1.15-2.4.jar Explosion't {explosiont@1.15-2.4 DONE}
		multibeds-1.15-1.6.7.jar Multi-Beds {multibeds@1.6.7 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		AkashicTome-1.3-13.jar Akashic Tome {akashictome@1.3-13 DONE}
		FluxNetworks-1.15.2-5.0.3-4.jar Flux Networks {fluxnetworks@1.15.2-5.0.3-4 DONE}
		enderchests-1.15-1.6.5.jar EnderChests {enderchests@1.6.5 DONE}
		betbeacpl_1.15-1.1.jar Better Beacon Placement {betbeacpl@1.1 DONE}
		obfuscate-0.5.0-1.15.2.jar Obfuscate {obfuscate@0.5.0 DONE}
		Clef-1.15.2-8.0.1.jar Clef {clef@8.0.1 DONE}
		subpocket-1.15-5.0.0.1.jar subpocket {subpocket@1.15-5.0.0.1 DONE}
		structurize-0.13.64-ALPHA.jar Structurize {structurize@0.13.64-ALPHA DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		Vampirism-1.15.2-1.7.0.jar Vampirism {vampirism@1.7.0 DONE, teamlapenlib@1.7.0 DONE}
		Enderthing-1.15.2-1.0.1.jar Enderthing {enderthing@1.0.1 DONE}
		VillagersRespawn-1.15.2-1.0.0.0.jar Villagers Respawn  Mod {villagersrespawn@1.0.0.0 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		CodeChickenLib-1.15.2-3.3.4.395-universal.jar CodeChicken Lib {codechickenlib@3.3.4.395 DONE}
		endercompass-1.1-1.15.2.jar Ender Compass {endercompass@1.1 DONE}
		botanicalmachinery-1.15.2-0.1.1.jar Botanical Machinery {botanicalmachinery@0.1.1 DONE}
		parachutemod-1.15.2-3.0.2-479.jar Parachute Mod NG {parachutemod@1.15.2-3.0.2-479 DONE}
		Morph-o-Tool-1.3-23.jar Morph-o-Tool {morphtool@1.3-23 DONE}
		EnderMail-1.15.2-1.1.3.jar Ender Mail {endermail@1.15.2-1.1.3 DONE}
		Kingdom+Keys+1.15.2-2.0.0.1.jar Kingdom Keys {kingdomkeys@2.0.0.1 DONE}
		bml-1.15.2-1.1.2.jar BML {blackdogsmoddinglibrary@1.1.2 DONE}
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: 
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

What can I do?

**Comment by Wehavecookies56** [comment]
This doesn't look like it has anything to do with Kingdom Keys, not sure what to suggest other than to do a clean installation

**Comment by HyperMan19680** [comment]
I'm well aware, but it only started happening after installing your mod.

**Comment by Wehavecookies56** [comment]
Try deleting your config folder
