### ISSUE TITLE
Game crashes when the ability key is pressed or when falling and no abilities are equipped

### ISSUE THREAD

**Issue by DanDragonWolf** [Wehavecookies56/Kingdom-Keys#10]
If I don't have an ability that is activated by jump or the ability key equipped, the game crashes when I press the ability key or fall. Here is a crash report: [https://pastebin.com/g5daqn7t](https://pastebin.com/g5daqn7t)

**Comment by DanDragonWolf** [comment]
I also found out that if I get the abilities, then remove them via commands, then the the game doesn't crash. It also doesn't crash in creative.

**Comment by DanDragon401** [comment]
Now it's crashing when I fall. I can't even go to the Station of Awakening without the game crashing due to it crashing if I fall..

**Comment by DanDragonWolf** [comment]
Fixed on Discord
