### ISSUE TITLE
Epic Fight + Drive Form Compatibility [REQUEST]

### ISSUE THREAD

**Issue by NoWayCj** [Wehavecookies56/Kingdom-Keys#14]
I don't know if this is on your end or Epic Fights, but drive forms don't seem to register for it. The armor's animations are stunted. Magic and shotlocks work fine, this is the only thing I seem to have issues with. This isn't that big a deal for me since I can disable the visibility of the drive forms in the config, but that feels like a disservice. Just imagine Epic Fights combat system with drive forms. Sounds like literal perfection

**Comment by XxsjrapsxX** [comment]
i mean im pretty sure if you can figure out what the armor is called, you can add it to the custom armor section in configs and it might fix the issues but idk much about this stuff
