### ISSUE TITLE
Player logout when loked on entity has too much hp

### ISSUE THREAD

**Issue by Kevadroz** [Wehavecookies56/Kingdom-Keys#17]
When a entity has really high amounts of health (in the thousands, i believe) and you lock on it the client will 'crash' to the multiplayer menu.
Amount of HP per bar affects how much hp is needed to logout, making the requirement higher with bigger values.
There is no exceptions in the log, or crash reports, or any relevant information.

**Comment by Abelatox** [comment]
Do you have the crash log? If so provide it by using pastebin.com

**Comment by Kevadroz** [comment]
> Do you have the crash log? If so provide it by using pastebin.com

> There is no exceptions in the log, or crash reports, or any relevant information.

The game doesn't 'crash' it just throws you into a disconected screen, without any relevant info in the logs, debug log or any crash report. If there was any of that I whould have provided it already.

One thing I can say is that if I rejoin the singleplayer world it throws me to the "invalid player movement" screen, but I don't think there's any info there either.
