### ISSUE TITLE
Ender Dragon does not reward Valor XP

### ISSUE THREAD

**Issue by LuZanth** [Wehavecookies56/Kingdom-Keys#28]
Behavior: While in Valor form, hitting the Ender dragon with weapons rewards 0 Valor xp per hit.

Expected: While in Valor form, hitting the Ender dragon rewards 1 Valor xp per hit.

Tested on Respawned Ender Dragon using dual wielded Wooden Sticks(Kingdom Keys)

Using version 2.1.2.2 as part of the Key Keeper JRPG Modpack

**Comment by Wehavecookies56** [comment]
It took way too long but finally fixed e42818d3520c5853d9d1ad41e4276ad593048ccf
