### ISSUE TITLE
Ticking Player Crash whilst Kingdom Keys is installed

### ISSUE THREAD

**Issue by UxerhintTV** [Wehavecookies56/Kingdom-Keys#29]
I had made a modpack with the Kingdom Keys mod in it. Originally it was going well but when the latest update to the mod came, I started having some problems. The game started with crashing with a "Ticking Player" (according to the crash notes) crash. I contacted CurseForge support because CurseForge is where I installed the mod, and they mentioned it involves the Kingdom Key mod. I uninstalled the mod from the pack and it started to work normal. I'm wondering if this an issue with only me or others have been having it and if I can fix it.

**Comment by Wehavecookies56** [comment]
Can you post your log file please though I think I know what caused it which I think I've managed to fix now and will post an update soon to curseforge

**Comment by UxerhintTV** [comment]
[crash-2022-08-15_11.53.02-server.txt](https://github.com/Wehavecookies56/Kingdom-Keys/files/9338584/crash-2022-08-15_11.53.02-server.txt)

**Comment by Wehavecookies56** [comment]
Should be fixed in 2.1.6.1
