### ISSUE TITLE
Suggestion: Use RegisterCommandsEvent to register commands

### ISSUE THREAD

**Issue by JustRed23** [Wehavecookies56/Kingdom-Keys#31]
Hi, I was wondering why you use a ServerStartingEvent instead of a RegisterCommandsEvent to register commands. I am currently working on a hybrid server that uses a different dispatcher than the vanilla one to register Forge commands and hooked it into the default RegisterCommandsEvent. Commands from your mod don't work because of that. Would you be able to change this?

**Comment by Wehavecookies56** [comment]
Did not know that event existed now, yeah I can change that
