### ISSUE TITLE
Portal crash and dimensional corruption 

### ISSUE THREAD

**Issue by ShAdOwFiRe1995** [Wehavecookies56/Kingdom-Keys#32]
https://paste.ee/p/lqzTS
Here is the data log for the issues that I'm currently having.
I have a dedicated server for a mod pack that includes Kingdom Keys, BYG, and about 26 other mods, and as long as I stay in the overworld, i have no issues. Every time that I enter the nether or the end, it stutters, and may let me load the terrain, or it may crash. If it crashes, then I can no longer enter that dimension, including leaving a dimension and going back to the overworld. I have tried using backups to solve the issue, but it is barely a temporary fix, because within 4 trips through the portal, it will stutter and crash again. I have tried removing some of the lower impact mods to see if they are what is causing the issue, but no luck there

**Comment by Wehavecookies56** [comment]
Have you confirmed it's Kingdom Keys causing the issue? There aren't any related errors in that log, when it crashes there should be a crash report

**Comment by ShAdOwFiRe1995** [comment]
![image-1](https://user-images.githubusercontent.com/130524698/235208488-45b04de4-00fd-4c7f-8f29-ae20b4831904.png)
I may have worded it incorrectly. More accurately, it forces a disconnect, and the above image is the error message that appears. Once the issue appears, we can no longer access that dimension. We have confirmed that removing kingdom Keys solves the issue. 
https://paste.ee/p/XkWTF there is also this log, though i don't know if it will help, it doesn't have an actual crash log stored for it

**Comment by Wehavecookies56** [comment]
Ah by any chance did you make a party? There's a bug that we'll have a update out soon to fix that, that causes them to duplicate a lot, for a temp fix, in your world folder in the data folder for the dimensions you can delete the capabilities.dat or use an NBT editor to remove the party data

**Comment by ShAdOwFiRe1995** [comment]
We did indeed create a party. Thank you for the solution, we will test that out as soon as we can
