### ISSUE TITLE
1.19.2- ``No Class Found Definition`` Startup Crash ``Kingdom Keys-1.19.2-2.3.2.0``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wehavecookies56/Kingdom-Keys#38]
Forge 43.2.23
Version Kingdom Keys-1.19.2-2.3.2.0

Crash Log
https://gist.github.com/P3rf3ctXZer0/1403a75f672da4d2a23a85d9bc6d3858

Log
https://gist.github.com/P3rf3ctXZer0/df21f48aa0e491341fb6bf99888d4978

**Comment by Wehavecookies56** [comment]
Will have an update out soon with this fixed
