### ISSUE TITLE
1.19.2 - ``Unable to get passed initial startup menu`` with ``AchievementOptimizer-1.19.2-1.0.2.jar by big_energy `` present in same pack.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wehavecookies56/Kingdom-Keys#39]
https://dl.dropboxusercontent.com/scl/fi/po8aauhmhl9yhh9nov71m/javaw_pR11a6g3Jz.gif?rlkey=tedivbh2dvm65zgwv1g6dstqf&dl=0

It seems that you can no longer get passed the start menu because you never get sent to the awakening room.

Kingdom Keys-1.19.2-2.3.2.1.jar

I will be sharing it with that dev as well.

**Comment by Wehavecookies56** [comment]
This is due to a bug with vanilla that was fixed in 1.19.3 if you exit your world then load it again it will work
