### ISSUE TITLE
Shaders incompatible with 3d weapons and blocks (Moogle Projector, Pedestal, Magical Chest)

### ISSUE THREAD

**Issue by DanDragonWolf** [Wehavecookies56/Kingdom-Keys#4]
I was setting up shaders on optifine, and when I turned them on, the textures for the 3d weapons and blocks became black and purple.

**Comment by Abelatox** [comment]
Try restarting after loading the shaderpack

**Comment by DanDragonWolf** [comment]
Lol, I restarted after turning on the shader pack a minute ago because my game crashed and turned off the shader pack. I thought I broke the textures but then when I turned the shader pack back on the textures started working. Thanks!

**Comment by Abelatox** [comment]
I'm glad it works!
