### ISSUE TITLE
Essential Mod possible incompatability? 1.19.2 crash on Death

### ISSUE THREAD

**Issue by AlsendDrake** [Wehavecookies56/Kingdom-Keys#49]
Mod version: 2.3.4
Minecraft version: 1.19.2
Forge version:  43.3.5

On death of any player when using Essential, game crashes. Exit code -1 with no log I can see. Possible incompatability?

**Comment by Wehavecookies56** [comment]
Apologies, we are no longer supporting 1.19.2 as it's difficult for us to maintain multiple versions
