### ISSUE TITLE
1.18.2 Crash due to "mobData is null"

### ISSUE THREAD

**Issue by BritneyMc0206** [Wehavecookies56/Kingdom-Keys#53]
My game keeps crashing with the error:
[java.lang.NullPointerException: Cannot invoke "online.kingdomkeys.kingdomkeys.capability.IGlobalCapabilities.getLevel()" because "mobData" is null]
I'm able to load my game & move around a bit, but it randomly crashes with this error. I have tried disabling the Heartless spawning, but there's no change.
I do have other mods that mess with mobs & leveling, but I have no idea how to pinpoint which mod, if any, are incompatible with Kingdom Keys.

[crash-2024-03-18_16.37.14-server.txt](https://github.com/Wehavecookies56/Kingdom-Keys/files/14642350/crash-2024-03-18_16.37.14-server.txt)

**Comment by Wehavecookies56** [comment]
Apologies, we are no longer supporting 1.18.2 as it's difficult for us to maintain multiple versions
