### ISSUE TITLE
Mod Compatibility and Moogles

### ISSUE THREAD

**Issue by SethSilver** [Wehavecookies56/Kingdom-Keys#6]
One can u make it so that mobs from other Mods can drop the xp and gummy. Second can u pls add to the mod page where to find moogles CAUSE I CAN'T FIND ANY. Do they spawn in villages their own separate structure, if so what biomes?

**Comment by Wehavecookies56** [comment]
For xp that will be implemented in the future, by gummy you mean the munny if so same answer for xp. 
Moogles can be found in almost every biome and they spawn a lot surprised you haven't found any.

**Comment by SethSilver** [comment]
well now I know they spawn anywhere I thought they spawned in a village or something. I'll keep a better eye out. if I have a problem I'll re-open the issue. To note I'm using Terraforge for terrain gen but that shouldn't affect it right?
