### ISSUE TITLE
Dire Plant Ticking Entity Crash

### ISSUE THREAD

**Issue by Frogperson** [Wehavecookies56/Kingdom-Keys#8]
It looks like the Dire Plant from this mod is causing the server to crash with a Ticking Entity error.

crash-report: https://mclo.gs/YgvRbbC

**Comment by Milliardo-V** [comment]
The same happens to me
-- Entity being ticked --
Details:
	Entity Type: kingdomkeys:dire_plant (online.kingdomkeys.kingdomkeys.entity.mob.DirePlantEntity)
	Entity ID: 565
	Entity Name: Dire Plant
	Entity's Exact location: 39.50, 63.00, 14.50
	Entity's Block location: World: (39,63,14), Chunk: (at 7,3,14 in 2,0; contains blocks 32,0,0 to 47,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

**Comment by AsessionGuy** [comment]
Same happened four times to me today using Kingdom Keys 1.16.4-2.0.1.7 and Forge server1.16.5-36.1.0.
I'm uploading the last crash crash-report file but it's practically the same for the rest.

[crash-2021-03-26_19.53.06-server.txt](https://github.com/Wehavecookies56/Kingdom-Keys/files/6214798/crash-2021-03-26_19.53.06-server.txt)

**Comment by Wehavecookies56** [comment]
Fixed in ac102c5fb5f85996d68d081d8d35ee8ce87ac4bb
Included in 2.0.1.8 now https://www.curseforge.com/minecraft/mc-mods/kingdom-keys-re-coded/files/3252357
