### ISSUE TITLE
Unable to rejoin a world after death

### ISSUE THREAD

**Issue by cr4pshooter** [Wehavecookies56/Kingdom-Keys#90]
Mod version: .... 2.4.1
Minecraft version: .... 1.20.1
Forge version:  .... 47.3.0

Describe what the bug is, how to reproduce, when it happened, etc.
Upon death my game crashed, and each subsequent rejoin leads to another crash. Similar issues are marked as "resolved" but there's no explanation of a fix, just a link to a separate document filled with code (and no explanation of how to use it)

(attach log file)
[crash-2024-07-12_07.39.43-client.txt](https://github.com/user-attachments/files/16194277/crash-2024-07-12_07.39.43-client.txt)

**Comment by Wehavecookies56** [comment]
Just posted an update that fixes this! 2.4.2

**Comment by cr4pshooter** [comment]
Love my timing for posting this lmao thank you!!
